### ISSUE TITLE
Repo's value proposal?

### ISSUE THREAD

**Issue by CxrlosKenobi** [giovanesantossilva/react-leaflet-draft#2]

**Comment by giovanesantossilva** [comment]
**Hello, my repository solved a problem found in alex3165 in onCreated caused by useEfect.**
And I have rewritten it making it more performant and easier for new implementations! 
If you want to suggest something I can analyze to implement!

**About the non-updated states could you give me an example, because I believe that with mine you won't have this problem!**

**Comment by CxrlosKenobi** [comment]
> **Hello, my repository solved a problem found in alex3165 in onCreated caused by useEfect.** And I have rewritten it making it more performant and easier for new implementations! If you want to suggest something I can analyze to implement!
> 
> **About the non-updated states could you give me an example, because I believe that with mine you won't have this problem!**

Sounds great!;
I would love your repo if so. I attached the issue where I explain it all, below:
- https://github.com/alex3165/react-leaflet-draw/issues/154
